-- Supabase Database Schema for V-LINK

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('farmer', 'buyer', 'delivery', 'labor', 'vendor')),
    language TEXT DEFAULT 'ta' CHECK (language IN ('ta', 'en')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to profiles" 
    ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profile" 
    ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow users to insert their own profile" 
    ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);


-- 2. Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_name TEXT NOT NULL,
    quantity NUMERIC NOT NULL CHECK (quantity >= 0),
    unit TEXT NOT NULL DEFAULT 'kg',
    price NUMERIC NOT NULL CHECK (price >= 0),
    location TEXT NOT NULL,
    farmer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    image TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to products" 
    ON public.products FOR SELECT USING (true);

CREATE POLICY "Allow farmers to manage their own products" 
    ON public.products FOR ALL USING (auth.uid() = farmer_id);


-- 3. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    buyer_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'in_transit', 'delivered')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to read their own orders" 
    ON public.orders FOR SELECT USING (
        auth.uid() = buyer_id OR 
        auth.uid() IN (SELECT farmer_id FROM public.products WHERE id = product_id)
    );

CREATE POLICY "Allow buyers to place orders" 
    ON public.orders FOR INSERT WITH CHECK (auth.uid() = buyer_id);

CREATE POLICY "Allow orders update" 
    ON public.orders FOR UPDATE USING (true);


-- 4. Delivery Jobs Table
CREATE TABLE IF NOT EXISTS public.delivery_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'assigned', 'delivered')),
    delivery_partner_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.delivery_jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to delivery jobs" 
    ON public.delivery_jobs FOR SELECT USING (true);

CREATE POLICY "Allow delivery partners to update jobs" 
    ON public.delivery_jobs FOR UPDATE USING (true);

CREATE POLICY "Allow delivery jobs insert" 
    ON public.delivery_jobs FOR INSERT WITH CHECK (true);


-- 5. Labor Jobs Table
CREATE TABLE IF NOT EXISTS public.labor_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    wage NUMERIC NOT NULL CHECK (wage >= 0),
    location TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'applied', 'filled')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.labor_jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to labor jobs" 
    ON public.labor_jobs FOR SELECT USING (true);

CREATE POLICY "Allow users to manage labor jobs" 
    ON public.labor_jobs FOR ALL USING (true);


-- 6. Wallet Transactions Table
CREATE TABLE IF NOT EXISTS public.wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount NUMERIC NOT NULL CHECK (amount >= 0),
    transaction_type TEXT NOT NULL CHECK (transaction_type IN ('credit', 'debit')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to view their own transactions" 
    ON public.wallet_transactions FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow transaction insertion" 
    ON public.wallet_transactions FOR INSERT WITH CHECK (auth.uid() = user_id OR auth.uid() IS NOT NULL);


-- 7. Market Prices Table
CREATE TABLE IF NOT EXISTS public.market_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commodity_name TEXT NOT NULL,
    market_name TEXT NOT NULL,
    district TEXT NOT NULL,
    state TEXT NOT NULL,
    min_price NUMERIC NOT NULL CHECK (min_price >= 0),
    max_price NUMERIC NOT NULL CHECK (max_price >= 0),
    modal_price NUMERIC NOT NULL CHECK (modal_price >= 0),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    -- Unique constraint to support upsert operations
    CONSTRAINT unique_market_commodity UNIQUE (commodity_name, market_name, district, state)
);

ALTER TABLE public.market_prices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to market prices" 
    ON public.market_prices FOR SELECT USING (true);

CREATE POLICY "Allow authenticated insert/update to market prices" 
    ON public.market_prices FOR ALL USING (true);

-- Migration to add language to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'ta' CHECK (language IN ('ta', 'en'));

-- 8. Scan History Table
CREATE TABLE IF NOT EXISTS public.scan_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    image_url TEXT,
    disease_name TEXT NOT NULL,
    confidence NUMERIC NOT NULL,
    treatment JSONB,
    prevention TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.scan_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to view their own scans" 
    ON public.scan_history FOR SELECT USING (auth.uid() = user_id OR auth.uid() IS NULL);

CREATE POLICY "Allow users to save their own scans" 
    ON public.scan_history FOR INSERT WITH CHECK (auth.uid() = user_id OR auth.uid() IS NULL OR auth.uid() IS NOT NULL);

-- 9. Farms Table
CREATE TABLE IF NOT EXISTS public.farms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    name TEXT,
    image_url TEXT,
    village TEXT NOT NULL,
    district TEXT NOT NULL,
    state TEXT NOT NULL,
    gps_location TEXT,
    land_size NUMERIC NOT NULL,
    land_unit TEXT NOT NULL CHECK (land_unit IN ('acres', 'hectares')),
    soil_type TEXT NOT NULL,
    water_source TEXT NOT NULL,
    primary_crop TEXT NOT NULL,
    secondary_crop TEXT,
    sowing_date DATE NOT NULL,
    expected_harvest_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.farms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to view their own farms" ON public.farms FOR SELECT USING (auth.uid() = user_id OR auth.uid() IS NULL);
CREATE POLICY "Allow users to manage their own farms" ON public.farms FOR ALL USING (auth.uid() = user_id OR auth.uid() IS NULL OR auth.uid() IS NOT NULL);

-- 10. Farm Expenses Table
CREATE TABLE IF NOT EXISTS public.farm_expenses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id UUID REFERENCES public.farms(id) ON DELETE CASCADE,
    category TEXT NOT NULL CHECK (category IN ('seeds', 'fertilizers', 'pesticides', 'rentals', 'labour', 'transport', 'misc')),
    amount NUMERIC NOT NULL CHECK (amount >= 0),
    description TEXT,
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.farm_expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to view their own farm expenses" ON public.farm_expenses FOR SELECT USING (true);
CREATE POLICY "Allow users to manage their own farm expenses" ON public.farm_expenses FOR ALL USING (true);

-- 11. Farm Income Table
CREATE TABLE IF NOT EXISTS public.farm_income (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id UUID REFERENCES public.farms(id) ON DELETE CASCADE,
    buyer_name TEXT,
    crop_sold TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    price_per_unit NUMERIC NOT NULL,
    total_income NUMERIC NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.farm_income ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to view their own farm income" ON public.farm_income FOR SELECT USING (true);
CREATE POLICY "Allow users to manage their own farm income" ON public.farm_income FOR ALL USING (true);

-- 12. Scheme Applications Table
CREATE TABLE IF NOT EXISTS public.scheme_applications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    scheme_id TEXT NOT NULL,
    scheme_name TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.scheme_applications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to view their own scheme applications" ON public.scheme_applications FOR SELECT USING (auth.uid() = user_id OR auth.uid() IS NULL);
CREATE POLICY "Allow users to save their own scheme applications" ON public.scheme_applications FOR INSERT WITH CHECK (auth.uid() = user_id OR auth.uid() IS NULL OR auth.uid() IS NOT NULL);


